### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by EpicSupermind** [MegaApplePi/mdp-osu#12]
on the issues side, with all the problems, is there a way you can click on the text to teleport you to where the problem occured. 
Example: If i had a http:// link, i should be able to click on the text at the side to show me where the link is and easily change it to https://

**Comment by MegaApplePi** [comment]
I don't think electron can do that, but would it be a bit more helpful if it had tried to tell you where the line number was instead?

**Comment by MegaApplePi** [comment]
resolved by #20
