### ISSUE TITLE
add error check for more terms

### ISSUE THREAD

**Issue by MegaApplePi** [MegaApplePi/mdp-osu#35]
- "mapper", "mappers"
  - should be "creator", "creators"
- "map", "maps"
  - should be "beatmap", "beatmaps"

others may appear here

**Comment by EpicSupermind** [comment]
This would be under the ASG section, under `Old Names` (considering removing Game Mode), right?

**Comment by MegaApplePi** [comment]
probably under `Terminology` in the ASG tab

**Comment by EpicSupermind** [comment]
new thing?

**Comment by MegaApplePi** [comment]
![electron_2017-07-13_12-49-12](https://user-images.githubusercontent.com/14264992/28180088-af0a72c8-67c9-11e7-8671-482b0dca2fe8.png)
yeah, probably something like this
... the `Old Game Mode Names` will probably be replace by this new one
